const API_BASE = "http://localhost:8000";

interface Brief {
  problem_summary: string;
  likely_users: string[];
  recommended_solution_type: string;
  clarifying_questions: string[];
  risks: string[];
  suggested_next_action: string;
  model_used: string;
}

interface TriageRequest {
  id: string;
  raw_text: string;
  submitted_by: string | null;
  created_at: string;
  status: string;
  owner: string | null;
  priority: string;
  notes: string | null;
  brief: Brief | null;
}

function requireEl<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Expected element #${id} to exist`);
  return el as T;
}

const app = requireEl<HTMLElement>("app");
const navSubmit = requireEl<HTMLButtonElement>("nav-submit");
const navQueue = requireEl<HTMLButtonElement>("nav-queue");

async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });
  if (!res.ok) throw new Error(`Request failed (${res.status})`);
  return res.json();
}

function setActiveNav(which: "submit" | "queue"): void {
  navSubmit.classList.toggle("active", which === "submit");
  navQueue.classList.toggle("active", which === "queue");
}

// ---------- Submit ----------
function renderSubmitView(): void {
  setActiveNav("submit");
  app.innerHTML = `
    <div class="card">
      <h2>Submit a Request</h2>
      <textarea id="raw_text" rows="5" placeholder="Describe the request..."></textarea>
      <button class="primary" id="submit-btn">Generate Brief</button>
    </div>
    <div id="result"></div>
  `;
  requireEl<HTMLButtonElement>("submit-btn").addEventListener("click", async () => {
    const text = requireEl<HTMLTextAreaElement>("raw_text").value;
    if (text.length < 10) { alert("Please write at least a sentence."); return; }
    const req = await api<TriageRequest>("/requests", {
      method: "POST",
      body: JSON.stringify({ raw_text: text }),
    });
    const b = req.brief!;
    requireEl<HTMLElement>("result").innerHTML = `
      <div class="card">
        <h3>Brief</h3>
        <p><b>Summary:</b> ${b.problem_summary}</p>
        <p><b>Likely users:</b> ${b.likely_users.join(", ")}</p>
        <p><b>Solution type:</b> ${b.recommended_solution_type}</p>
        <p><b>Clarifying questions:</b></p>
        <ul>${b.clarifying_questions.map(q => `<li>${q}</li>`).join("")}</ul>
        <p><b>Risks:</b></p>
        <ul>${b.risks.map(r => `<li>${r}</li>`).join("")}</ul>
        <p><b>Next action:</b> ${b.suggested_next_action}</p>
        <p><small>Generated by ${b.model_used} · id ${req.id}</small></p>
      </div>
    `;
  });
}

// ---------- Queue ----------
async function renderQueueView(): Promise<void> {
  setActiveNav("queue");
  const requests = await api<TriageRequest[]>("/requests");
  app.innerHTML = `
    <div class="card">
      <h2>Triage Queue (${requests.length})</h2>
      ${requests.map(r => `
        <div class="queue-row" data-id="${r.id}">
          <b>${r.status}</b> — ${r.raw_text.slice(0, 60)}
          <span style="float:right">${r.priority}</span>
        </div>
      `).join("")}
    </div>
  `;
  app.querySelectorAll<HTMLElement>(".queue-row").forEach(row => {
    row.addEventListener("click", () => renderDetailView(row.dataset.id!));
  });
}

// ---------- Detail ----------
async function renderDetailView(id: string): Promise<void> {
  const req = await api<TriageRequest>(`/requests/${id}`);
  const b = req.brief;
  app.innerHTML = `
    <button class="back" id="back-btn">&larr; Back to queue</button>
    <div class="card">
      <h2>Request ${req.id}</h2>
      <p>${req.raw_text}</p>
    </div>
    ${b ? `
    <div class="card">
      <h3>Brief</h3>
      <p><b>Summary:</b> ${b.problem_summary}</p>
      <p><b>Solution type:</b> ${b.recommended_solution_type}</p>
    </div>` : ""}
    <div class="card">
      <h3>Triage</h3>
      <label>Status</label>
      <select id="f-status">
        ${["new","needs_info","in_triage","accepted","rejected","done"]
          .map(s => `<option value="${s}" ${s === req.status ? "selected" : ""}>${s}</option>`).join("")}
      </select>
      <label>Priority</label>
      <select id="f-priority">
        ${["low","medium","high"].map(p => `<option value="${p}" ${p === req.priority ? "selected" : ""}>${p}</option>`).join("")}
      </select>
      <label>Owner</label>
      <input id="f-owner" value="${req.owner ?? ""}" placeholder="unassigned">
      <label>Notes</label>
      <textarea id="f-notes" rows="3">${req.notes ?? ""}</textarea>
      <button class="primary" id="save-btn">Save</button>
    </div>
    <div class="card">
      <h3>Audit History</h3>
      <div id="audit">Loading…</div>
    </div>
  `;
  requireEl<HTMLButtonElement>("back-btn").addEventListener("click", renderQueueView);
  requireEl<HTMLButtonElement>("save-btn").addEventListener("click", () => saveTriage(req.id));
  loadAudit(req.id);
}

async function saveTriage(id: string): Promise<void> {
  const payload = {
    status: requireEl<HTMLSelectElement>("f-status").value,
    priority: requireEl<HTMLSelectElement>("f-priority").value,
    owner: requireEl<HTMLInputElement>("f-owner").value || null,
    notes: requireEl<HTMLTextAreaElement>("f-notes").value || null,
  };
  await api(`/requests/${id}`, { method: "PATCH", body: JSON.stringify(payload) });
  loadAudit(id);
  alert("Saved.");
}

async function loadAudit(id: string): Promise<void> {
  const entries = await api<any[]>(`/requests/${id}/audit`);
  requireEl<HTMLElement>("audit").innerHTML = entries.length
    ? entries.map(e => `<div>${e.field}: ${e.old_value} → ${e.new_value}</div>`).join("")
    : "No changes yet.";
}

navSubmit.addEventListener("click", renderSubmitView);
navQueue.addEventListener("click", renderQueueView);
renderSubmitView();