const API_BASE = "http://localhost:8000";
const TOKEN_KEY = "reviewerToken";

interface Brief {
  problem_summary: string;
  likely_users: string[];
  recommended_solution_type: string;
  clarifying_questions: string[];
  risks: string[];
  suggested_next_action: string;
  model_used: string;
}

interface TriageRequest {
  id: string;
  raw_text: string;
  submitted_by: string | null;
  created_at: string;
  status: string;
  owner: string | null;
  priority: string;
  notes: string | null;
  duplicate_of: string | null;
  brief: Brief | null;
}

function requireEl<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Expected element #${id} to exist`);
  return el as T;
}

const app = requireEl<HTMLElement>("app");
const navSubmit = requireEl<HTMLButtonElement>("nav-submit");
const navQueue = requireEl<HTMLButtonElement>("nav-queue");

function getToken(): string {
  return localStorage.getItem(TOKEN_KEY) || "";
}
function setToken(t: string): void {
  t ? localStorage.setItem(TOKEN_KEY, t) : localStorage.removeItem(TOKEN_KEY);
}

async function api<T>(path: string, options: RequestInit = {}, needsAuth = false): Promise<T> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (needsAuth) {
    const t = getToken();
    if (t) headers["X-Reviewer-Token"] = t;
  }
  const res = await fetch(`${API_BASE}${path}`, { headers, ...options });
  if (!res.ok) throw new Error(`Request failed (${res.status})`);
  return res.json();
}

function setActiveNav(which: "submit" | "queue"): void {
  navSubmit.classList.toggle("active", which === "submit");
  navQueue.classList.toggle("active", which === "queue");
}

// ---------- Submit ----------
function renderSubmitView(): void {
  setActiveNav("submit");
  app.innerHTML = `
    <div class="card">
      <h2>Submit a Request</h2>
      <textarea id="raw_text" rows="5" placeholder="Describe the request..."></textarea>
      <button class="primary" id="submit-btn">Generate Brief</button>
    </div>
    <div id="result"></div>
  `;
  requireEl<HTMLButtonElement>("submit-btn").addEventListener("click", async () => {
    const text = requireEl<HTMLTextAreaElement>("raw_text").value;
    if (text.length < 10) { alert("Please write at least a sentence."); return; }
    const req = await api<TriageRequest>("/requests", {
      method: "POST",
      body: JSON.stringify({ raw_text: text }),
    });
    const b = req.brief!;
    const dupBanner = req.duplicate_of
      ? `<div class="dup-banner">⚠ Looks similar to an existing request (${req.duplicate_of}) — check the queue.</div>`
      : "";
    requireEl<HTMLElement>("result").innerHTML = `
      ${dupBanner}
      <div class="card">
        <h3>Brief</h3>
        <p><b>Summary:</b> ${b.problem_summary}</p>
        <p><b>Likely users:</b> ${b.likely_users.join(", ")}</p>
        <p><b>Solution type:</b> ${b.recommended_solution_type}</p>
        <p><b>Clarifying questions:</b></p>
        <ul>${b.clarifying_questions.map(q => `<li>${q}</li>`).join("")}</ul>
        <p><b>Risks:</b></p>
        <ul>${b.risks.map(r => `<li>${r}</li>`).join("")}</ul>
        <p><b>Next action:</b> ${b.suggested_next_action}</p>
        <p><small>Generated by ${b.model_used} · id ${req.id}</small></p>
      </div>
    `;
  });
}

// ---------- Queue ----------
async function renderQueueView(): Promise<void> {
  setActiveNav("queue");
  app.innerHTML = `
    <div class="card">
      <label>Reviewer token (only needed if backend has REVIEWER_TOKEN set)</label>
      <div class="token-row">
        <input id="token-input" type="password" value="${getToken()}">
        <button id="save-token-btn">Save</button>
      </div>
    </div>
    <div id="queue-body">Loading…</div>
  `;
  requireEl<HTMLButtonElement>("save-token-btn").addEventListener("click", () => {
    setToken(requireEl<HTMLInputElement>("token-input").value.trim());
    loadQueue();
  });
  await loadQueue();
}

async function loadQueue(): Promise<void> {
  const body = requireEl<HTMLElement>("queue-body");
  try {
    const requests = await api<TriageRequest[]>("/requests", {}, true);
    body.innerHTML = `
      <div class="card">
        <div style="display:flex;justify-content:space-between;align-items:center;">
          <h2 style="margin:0;">Triage Queue (${requests.length})</h2>
          <a href="${API_BASE}/requests/export/csv">Export CSV</a>
        </div>
        ${requests.map(r => `
          <div class="queue-row" data-id="${r.id}">
            <div>
              <span class="status-badge">${r.status}</span> — ${r.raw_text.slice(0, 60)}
              ${r.duplicate_of ? '<span class="dup-tag">possible dup</span>' : ""}
            </div>
            <span class="pill pill-${r.priority}">${r.priority}</span>
          </div>
        `).join("")}
      </div>
    `;
    body.querySelectorAll<HTMLElement>(".queue-row").forEach(row => {
      row.addEventListener("click", () => renderDetailView(row.dataset.id!));
    });
  } catch (err) {
    body.innerHTML = `<div class="card">Failed to load queue: ${(err as Error).message}</div>`;
  }
}

// ---------- Detail ----------
async function renderDetailView(id: string): Promise<void> {
  const req = await api<TriageRequest>(`/requests/${id}`, {}, true);
  const b = req.brief;
  app.innerHTML = `
    <button class="back" id="back-btn">&larr; Back to queue</button>
    <div class="card">
      <h2>Request ${req.id}</h2>
      <p>${req.raw_text}</p>
    </div>
    ${b ? `
    <div class="card">
      <h3>Brief</h3>
      <p><b>Summary:</b> ${b.problem_summary}</p>
      <p><b>Solution type:</b> ${b.recommended_solution_type}</p>
    </div>` : ""}
    <div class="card">
      <h3>Triage</h3>
      <label>Status</label>
      <select id="f-status">
        ${["new","needs_info","in_triage","accepted","rejected","done"]
          .map(s => `<option value="${s}" ${s === req.status ? "selected" : ""}>${s}</option>`).join("")}
      </select>
      <label>Priority</label>
      <select id="f-priority">
        ${["low","medium","high"].map(p => `<option value="${p}" ${p === req.priority ? "selected" : ""}>${p}</option>`).join("")}
      </select>
      <label>Owner</label>
      <input id="f-owner" value="${req.owner ?? ""}" placeholder="unassigned">
      <label>Notes</label>
      <textarea id="f-notes" rows="3">${req.notes ?? ""}</textarea>
      <button class="primary" id="save-btn">Save</button>
    </div>
    <div class="card">
      <h3>Audit History</h3>
      <div id="audit">Loading…</div>
    </div>
  `;
  requireEl<HTMLButtonElement>("back-btn").addEventListener("click", renderQueueView);
  requireEl<HTMLButtonElement>("save-btn").addEventListener("click", () => saveTriage(req.id));
  loadAudit(req.id);
}

async function saveTriage(id: string): Promise<void> {
  const payload = {
    status: requireEl<HTMLSelectElement>("f-status").value,
    priority: requireEl<HTMLSelectElement>("f-priority").value,
    owner: requireEl<HTMLInputElement>("f-owner").value || null,
    notes: requireEl<HTMLTextAreaElement>("f-notes").value || null,
  };
  await api(`/requests/${id}`, { method: "PATCH", body: JSON.stringify(payload) }, true);
  loadAudit(id);
  alert("Saved.");
}

async function loadAudit(id: string): Promise<void> {
  const entries = await api<any[]>(`/requests/${id}/audit`, {}, true);
  requireEl<HTMLElement>("audit").innerHTML = entries.length
    ? entries.map(e => `<div>${e.field}: ${e.old_value} → ${e.new_value}</div>`).join("")
    : "No changes yet.";
}

navSubmit.addEventListener("click", renderSubmitView);
navQueue.addEventListener("click", renderQueueView);
renderSubmitView();